# Generated by Django 3.1.5 on 2021-01-12 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import macaddress.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', macaddress.fields.MACAddressField(help_text="A device's MAC address can be found on a sticker attached to the device.", integer=True, verbose_name='MAC address')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('authorized_until', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp', '-authorized_until'),
            },
        ),
    ]
